### ISSUE TITLE
Windows not show

### ISSUE THREAD

**Issue by sirepson** [RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-#1]
Can you help me? Why Windows EFI not show in OpenCore?

**Comment by RaffaySajjad** [comment]
> Can you help me? Why Windows EFI not show in OpenCore?

Please make sure your EFI contains a folder named “Microsoft”

**Comment by sirepson** [comment]
![image](https://user-images.githubusercontent.com/45273945/97972407-0d2b4800-1df7-11eb-8a29-eb904bd7c402.png)
This is my structure folder

**Comment by RaffaySajjad** [comment]
> ![image](https://user-images.githubusercontent.com/45273945/97972407-0d2b4800-1df7-11eb-8a29-eb904bd7c402.png)
> This is my structure folder
Strange. My EFI has the following structure and Windows is showing in the boot loader.
![Screen Shot 2020-11-03 at 3 13 41 PM](https://user-images.githubusercontent.com/25899678/97973031-41970800-1de7-11eb-83ac-0cda76863d72.png)
Can you boot into your Windows directly?

**Comment by sirepson** [comment]
I can boot into windows with F9 button and select EFI Windows Manually

**Comment by sirepson** [comment]
If I rename **bootmgfw-orig.efi** to **bootmgfw.efi** OpenCore not show and immediately boot to Windows

**Comment by RaffaySajjad** [comment]
> I can boot into windows with F9 button and select EFI Windows Manually

Unfortunately, not sure what’s the issue then. It’s spreading Windows entry for me in Opencore.

**Comment by RaffaySajjad** [comment]
> If I rename **bootmgfw-orig.efi** to **bootmgfw.efi** OpenCore not show and immediately boot to Windows

Yes. Do not rename. Otherwise OC cannot detect the Windows entry. Renaming used to be required on Clover only.

**Comment by sirepson** [comment]
@Tonymiugrey can you help me?

**Comment by sirepson** [comment]
I'm install Windows in PM981 and Hackintosh in Samsung 860 EVO (Different drive). Is that the cause of the problem?

**Comment by sirepson** [comment]
In config.plist (line 1432) there is your path
`PciRoot(0x0)/Pci(0x1,0x1)/Pci(0x0,0x0)/NVMe(0x1,11-22-33-44-55-66-77-88)/HD(1,GPT,00000000-0000-0000-0000-000000000000,0x800,0x64000)/\EFI\BOOT\BOOTX64.EFI`

Need to change or not?

**Comment by sirepson** [comment]
How about BIOS? Need to configure or not?

**Comment by RaffaySajjad** [comment]
@arepson Usually Opencore detects the path of Windows by itself. If it doesn't (you need to confirm the path through your BIOS) then probably you need to edit it. Secondly, you have Windows installed on PM981. I wonder this may be the case of issue.

**Comment by sirepson** [comment]
Can you upload all your EFI files? (Include Windows)?

**Comment by RaffaySajjad** [comment]
> Can you upload all your EFI files? (Include Windows)?

I don’t think that’s a good idea. Incompatibility between build version of Windows can make your Windows unbootable. 
On the side note, I think you should boot Windows  without Opencore as with OC you loose your Dedicated graphics card and all the peripherals not compatible with macOS.

**Comment by ghost** [comment]
Try to install windows on bootcamp.
