### ISSUE TITLE
Can I use your efi to boot on windows?

### ISSUE THREAD

**Issue by ghost** [RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-#3]

**Comment by RaffaySajjad** [comment]
For now, No. I’ll update the EFI in a few days to support this functionality.

**Comment by ghost** [comment]
OOHh , great man your efi is the only one with whom i can put my laptop to sleep on mac os !

**Comment by ghost** [comment]
I will wait for the update, but until then I will start it from f9 😉

**Comment by RaffaySajjad** [comment]
Glad I was able to help :)

**Comment by ghost** [comment]
I have solved the problem but now touchpad and brightness keys don t work on windows

**Comment by RaffaySajjad** [comment]
> I have solved the problem but now touchpad and brightness keys don t work on windows

What you did exactly?

**Comment by ghost** [comment]
I used some ACPI from tony ! Removed boot-args and disable some ACPI patches !

**Comment by sirepson** [comment]
Any update @RaffaySajjad?

**Comment by RaffaySajjad** [comment]
I'm not actively working on this project.
