### ISSUE TITLE
You have any problem with kernel panic due to NVMe SSD ?

### ISSUE THREAD

**Issue by ghost** [RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-#4]

**Comment by ghost** [comment]
After returning from sleep, it works perfectly for a while after it stops abruptly and restarts, and in the error report opens kernel panic.

**Comment by RaffaySajjad** [comment]
No. I'm not facing any kernel panic. Unless ofcourse, you have PM981.

**Comment by ghost** [comment]
No, I don t have PM981, I have a 970 evo 500 gb

**Comment by ghost** [comment]
![813E4BA6-EFAF-4AB2-A6C4-6E6E2C4C2965](https://user-images.githubusercontent.com/66947407/99884132-64714b00-2c34-11eb-9445-57e22bd007f8.jpeg)

**Comment by ghost** [comment]
You have macOS installed on NVMe SSD ?

**Comment by RaffaySajjad** [comment]
No idea why you are getting this. This release is actually rock solid for me. To answer your last question, yes both Windows and macOS are installed on the same SSD.

**Comment by ghost** [comment]
I will load to reinstall macOS and if I solve something I will come back!

**Comment by RaffaySajjad** [comment]
Sure

**Comment by ghost** [comment]
The problem has not been solved, so it manifests itself as follows, I put him to sleep and leave him for 5 minutes after I wake him up work perfect and put him back to sleep for 30 minutes, after 30 minutes I manage to wake him up and soon he suddenly restarts and kernel error panic nvme, please test this and how it behaves to you ! Thank you !

**Comment by ghost** [comment]
Do you have any idea how I could solve this problem?

**Comment by RaffaySajjad** [comment]
@VladAlexandru2000 I tried on my system. Even inducing multiple sleeps within short intervals, but still I'm getting no KP. What I can advise you is remove NVMEFamily.kext

**Comment by ghost** [comment]
I don t have any NVMEFamily.kext in my OC folder

**Comment by RaffaySajjad** [comment]
> I don t have any NVMEFamily.kext in my OC folder

Not exactly. If your SSD is natively supported then you don’t need it.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/66947407/99955396-f12f1c80-2d8c-11eb-8be2-c768336c43f8.jpg)

**Comment by RaffaySajjad** [comment]
I'm out of options.

**Comment by ghost** [comment]
What SSD you have ?

**Comment by RaffaySajjad** [comment]
Toshiba SSD: THNSN5128GPU7

**Comment by ghost** [comment]
Interesting is, your SSD has a controller from SAMSUNG !

**Comment by ghost** [comment]
What is the exact model of your laptop?

**Comment by ghost** [comment]
I will try to replace my ssd with and seagate firecuda 510 because this ssd have a phison controller !

**Comment by ghost** [comment]
With FireCuda 510 I solved the problem, I don't even need NVMeFix.kext absolutely everything works perfectly!

**Comment by RaffaySajjad** [comment]
Great you were able to fix the issue.
